package hashmaphashfunction.customhashmap;
import java.util.HashMap;
import java.util.Map;
public class CustomHashMapTest {
    public static void main(String[] args) {
        CustomHashMap customHashMap = new CustomHashMap();
        customHashMap.put("1", "one");
        customHashMap.put("2", "two");
        customHashMap.put("3", "three");
        customHashMap.put("4", "four");
        customHashMap.put("5", "five");
        customHashMap.put("6", "six");
        customHashMap.put("7", "seven");
        customHashMap.put("8", "eight");
        customHashMap.put("9", "nine");
        customHashMap.put("10", "ten");
        customHashMap.put("11", "eleven");
        customHashMap.put("12", "twelve");
        customHashMap.put("13", "thirteen");
        customHashMap.put("14", "fourteen");
        customHashMap.put("15", "fifteen");
        customHashMap.put("16", "sixteen");
        customHashMap.put("17", "seventeen");
        customHashMap.put("18", "eighteen");
        customHashMap.put("19", "nineteen");
        customHashMap.put("20", "twenty");
        customHashMap.put("21", "twenty one");
        customHashMap.put("22", "twenty two");
        customHashMap.put("23", "twenty three");
        customHashMap.put("24", "twenty four");
        customHashMap.put("25", "twenty five");
        customHashMap.put("26", "twenty six");
        customHashMap.put("27", "twenty seven");
        customHashMap.put("28", "twenty eight");
        customHashMap.put("29", "twenty nine");
        customHashMap.put("30", "thirty");
        customHashMap.put("31", "thirty one");
        customHashMap.put("32", "thirty two");
        customHashMap.put("33", "thirty three");
        customHashMap.put("34", "thirty four");
        customHashMap.put("35", "thirty five");
        customHashMap.put("36", "thirty six");
        customHashMap.put("37", "thirty seven");
        customHashMap.put("38", "thirty eight");
        customHashMap.put("39", "thirty nine");
        customHashMap.put("40", "forty");
        customHashMap.put("41", "forty one");
        customHashMap.put("42", "forty two");
        customHashMap.put("43", "forty three");
        customHashMap.put("44", "forty four");
        customHashMap.put("45", "forty five");
        System.out.println("Value for key 1: " + customHashMap.get("1"));
        System.out.println("Value for key 22: " + customHashMap.get("22"));
        System.out.println("Value for key 25: " + customHashMap.get("25"));
        customHashMap.remove ("25");
        customHashMap.put("25", "twenty five updated");
        System.out.println("Value for key 25: " + customHashMap.get("25"));
}
}
